### ISSUE TITLE
Mediator: java8  switch... case  don't support String type, suggest to change it to Enum type

### ISSUE THREAD

**Issue by kenzhaoyihui** [CyC2018/Design-Patterns#1]
This class "ConcreteMediator" used the `switch...case` , but java don't support the String type, so suggest to change to Enum type.

**Comment by CyC2018** [comment]
@kenzhaoyihui  JDK 1.7 support String in switch.

**Comment by kenzhaoyihui** [comment]
Yes, jdk 7 support that,  thanks. I will close this issue.
